// SPDX-License-Identifier: GPL-3.0
/*
    Copyright 2021 0KIMS association.

    This file is generated with [snarkJS](https://github.com/iden3/snarkjs).

    snarkJS is a free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    snarkJS is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
    License for more details.

    You should have received a copy of the GNU General Public License
    along with snarkJS. If not, see <https://www.gnu.org/licenses/>.
*/

pragma solidity >=0.7.0 <0.9.0;

// ============================================================================
// VEIL PROVENANCE NOTE (not part of the original snarkjs template):
//
// This file was generated by `snarkjs zkey export solidityverifier` from
// circuits/artifacts/solvency_final.zkey, which was itself produced by a
// real, local, single-contributor Groth16 trusted setup ceremony run
// against circuits/solvency.circom (see BUILD_NOTES.md for the full
// pipeline: circom compile -> local powersoftau ceremony -> groth16 setup
// -> single contribution -> this export).
//
// SINGLE-CONTRIBUTOR CEREMONY CAVEAT: the phase-2 (circuit-specific) zkey
// ceremony had exactly one contributor (this build). A production system
// would want a proper multi-party ceremony so no single party ever knew
// the toxic waste that could forge proofs. For a hackathon submission this
// is a documented, accepted limitation, not something to imply is
// production-grade.
//
// verifyProof()'s public input array (_pubSignals[4]) order, confirmed
// empirically by generating and verifying a real proof in this session,
// not just assumed from the circuit's public declaration order:
//   [0] = valid      (circuit output, always 1 for any proof that verifies)
//   [1] = threshold
//   [2] = orderId
//   [3] = commitment
//
// PIPELINE SAFETY NOTE: circuits/package.json's `export:verifier` script
// writes to build/SolvencyVerifier.sol, NOT directly here — on purpose,
// after this exact file got silently clobbered once during development by
// a re-run that wrote straight to this path. Publishing a freshly exported
// verifier here is a deliberate manual step (copy + re-apply the rename
// and this note), not an automatic one. See circuits/README.md.
//
// DO NOT hand-edit the verifyProof() logic itself below this note.
// Regenerate it from the circuit if solvency.circom changes — editing the
// exported verifier without re-running the ceremony would desynchronize it
// from the actual circuit and either break verification or silently
// accept invalid proofs.
// ============================================================================

contract SolvencyVerifier {
    // Scalar field size
    uint256 constant r    = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    // Base field size
    uint256 constant q   = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    // Verification Key data
    uint256 constant alphax  = 19196916329657669310197093144641103420014946268484789433711389087456975160929;
    uint256 constant alphay  = 14108068317045967798680009798924597045946962565043912427052922259958124720362;
    uint256 constant betax1  = 9465383807108843453319520501296708374324188584214947688485170883029631087207;
    uint256 constant betax2  = 4541321171773862288782667296353162597410340825347170501018547426599583608092;
    uint256 constant betay1  = 9620400361712401561084843485116097330387947343412593166303956149810438138630;
    uint256 constant betay2  = 6221364923437929442045328882123610018415885031782554465597982287114911887177;
    uint256 constant gammax1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant gammax2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant gammay1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 constant gammay2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 constant deltax1 = 15823441247397750833067552066317973149688158529954890075289105835130715581214;
    uint256 constant deltax2 = 8737055117836473842873619091948305696984511989155804137237676760107305336051;
    uint256 constant deltay1 = 18292151995548061946462706359201300996110121620418549396212382488435498157030;
    uint256 constant deltay2 = 21109407355619361951999410065004641094084745111399150997734206095296856551206;

    
    uint256 constant IC0x = 12942569966622002106003614491078905604203985864996495055796051717560320040987;
    uint256 constant IC0y = 7641441991112798193521516944309682264536599882261942306417189337337006955419;
    
    uint256 constant IC1x = 6245818176807260808423510846816148409455163822988347705618859537262437460470;
    uint256 constant IC1y = 18281378442043937771552679212517025598396877461285510197710829196773053700733;
    
    uint256 constant IC2x = 10278644876626573936602230354909136164801607658198313852975788420483867641540;
    uint256 constant IC2y = 17138125546597852699691549160439228420092751539557024548499889482415602649243;
    
    uint256 constant IC3x = 20041131928111746772721454773136079412204817857125666125220924360144672795618;
    uint256 constant IC3y = 10724012568265367756511600843281065301596617026464692119972967328193964872879;
    
    uint256 constant IC4x = 21879561143940178825989981219635755253389347165518491011669484891820959230798;
    uint256 constant IC4y = 18285378132816590381751252578458058017970165134931264236816720230892388624210;
    
 
    // Memory data
    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant pLastMem = 896;

    function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[4] calldata _pubSignals) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }
            
            // G1 function to multiply a G1 value(x,y) to value in an address
            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Compute the linear combination vk_x
                
                g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                
                g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                
                g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                
                g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(add(pMem, pVk)))
                mstore(add(_pPairing, 416), mload(add(pMem, add(pVk, 32))))


                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)


                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, pLastMem))

            // Validate that all evaluations ∈ F
            
            checkField(calldataload(add(_pubSignals, 0)))
            
            checkField(calldataload(add(_pubSignals, 32)))
            
            checkField(calldataload(add(_pubSignals, 64)))
            
            checkField(calldataload(add(_pubSignals, 96)))
            

            // Validate all evaluations
            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
             return(0, 0x20)
         }
     }
 }
